apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: openfaas
spec:
  ports:
  - port: 3000
    nodePort: 30300
    protocol: TCP
  selector:
    app: grafana
  type: NodePort
