apiVersion: v1
kind: Service
metadata:
  name: node-red
  namespace: node-red
  labels:
    app: node-red
spec:
  selector:
    app: node-red
  type: NodePort
  ports:
  - port: 1880
    targetPort: 1880
    protocol: TCP
    nodePort: 31880